### ISSUE TITLE
Random dad joke

### ISSUE THREAD

**Issue by brettlangdon** [cloudflare/receipt-printer#4]
If it is connected to the network, should also have it print a random dad joke via https://icanhazdadjoke.com/api

:)

I would be happy to submit a PR, but wasn't sure if you have it connected to a network or not.

**Comment by terinjokes** [comment]
There's a dad joke API? Finally, I've found my life calling. ;)

**Comment by jgrahamc** [comment]
This is a fun idea but this is intended to run internally and not have network access and I would rather not make it depend on the internet.

**Comment by brettlangdon** [comment]
No worries, figured that was the case.
